In [37]:
import pandas as pd
import numpy as np

In [38]:
datacrime=pd.read_csv("datacrime.csv")
datacrime

respon  predik1  predik2  predik3
0       11980      0.0     0.00    41.02
1       23123      1.0     4.25   127.56
2       29344      6.0    16.60   218.59
3       16656     10.0    57.86   306.64
4       11245      NaN      NaN      NaN
5      140494     77.0    50.98   442.95
6       28700      4.0    13.53   226.63
7       59459     34.0    55.79   439.73
8       74111     35.0    43.87   115.31
9      103590    141.0   130.69  1544.24
10      31601     29.0    90.25   722.02
11      25158     21.0    77.73  2605.96
12      40641     36.0    78.53   798.39
13      57140     59.0   100.51  1476.93
14      13132      NaN      NaN      NaN
15      30954      NaN      NaN      NaN
16      45532      0.0     0.00    89.94
17     180038     30.0    16.72   374.07
18      14869      2.0    13.24   112.50
19     261721    146.0    49.94   772.77
20      50889      NaN      NaN      NaN
21    7322564   2818.0    38.50  2097.71
22      26436      9.0    58.03   644.75
23      12183      1.0     8.07   145.20
24      16023     10.0    55.52   560.71
25      24692      9.0    29.18   204.23
26      13842      2.0    13.38   347.97
27      88693     42.0    45.10   894.51
28      11235     20.0   145.72  1143.90
29      28259     24.0    86.13   724.95
...       ...      ...      ...      ...
2185    48949     33.0    60.08  1691.21
2186    23252      4.0    14.99   741.91
2187    15066      3.0    19.13   216.85
2188    13198      1.0     7.37    73.73
2189    16829      1.0     5.07   324.66
2190    15372      1.0     6.28    43.98
2191    13333      4.0    29.14   254.93
2192    37825      7.0    17.72   255.74
2193    29885      7.0    18.83   492.40
2194    37520      3.0     7.14   228.53
2195    20319      3.0    13.00   485.18
2196    77759     56.0    69.62  1246.89
2197    14904      2.0     9.80   205.84
2198    12208      1.0     8.08   234.34
2199    25430      4.0    14.98    86.12
2200    92703      9.0    10.01   640.62
2201    24544     15.0    59.71   409.98
2202    14203      4.0    24.37   255.86
2203    27331      8.0    27.53  1996.15
2204    23875      6.0    21.95   288.98
2205    14804      6.0    32.87   372.56
2206    21732      6.0    26.90   228.66
2207    54021      5.0     9.46   285.73
2208    13131      1.0     7.81    46.85
2209    10567      0.0     0.00   132.87
2210    56216     30.0    49.46   545.75
2211    12251      4.0    33.09   124.10
2212    32824      5.0    13.61   353.83
2213    13547      2.0    15.71   691.17
2214    28898     19.0    62.80   918.89

[2215 rows x 4 columns]

In [39]:
#mengetahui banyak data missing value
np.sum(datacrime.isnull())

respon       0
predik1    209
predik2    209
predik3    222
dtype: int64

In [40]:
#statistika deskriptif tiap variabel
datacrime.describe()

respon      predik1      predik2      predik3
count  2.215000e+03  2006.000000  2006.000000  1993.000000
mean   5.311798e+04    28.058325    36.263175   589.290336
std    2.046203e+05   105.641105    34.247641   614.866306
min    1.000500e+04     0.000000     0.000000     0.000000
25%    1.436600e+04     2.000000    11.517500   161.690000
50%    2.279200e+04     7.000000    26.930000   374.070000
75%    4.302400e+04    19.000000    51.480000   794.410000
max    7.322564e+06  2818.000000   401.350000  4877.060000

In [41]:
#mengatasi missing value menggunakan nilai mean
datacrime1=datacrime
datacrime1['predik1']=datacrime['predik1'].fillna((datacrime1['predik1'].mean()))
datacrime1['predik2']=datacrime['predik2'].fillna((datacrime1['predik2'].mean()))
datacrime1['predik3']=datacrime['predik3'].fillna((datacrime1['predik3'].mean()))
datacrime1

respon      predik1     predik2      predik3
0       11980     0.000000    0.000000    41.020000
1       23123     1.000000    4.250000   127.560000
2       29344     6.000000   16.600000   218.590000
3       16656    10.000000   57.860000   306.640000
4       11245    28.058325   36.263175   589.290336
5      140494    77.000000   50.980000   442.950000
6       28700     4.000000   13.530000   226.630000
7       59459    34.000000   55.790000   439.730000
8       74111    35.000000   43.870000   115.310000
9      103590   141.000000  130.690000  1544.240000
10      31601    29.000000   90.250000   722.020000
11      25158    21.000000   77.730000  2605.960000
12      40641    36.000000   78.530000   798.390000
13      57140    59.000000  100.510000  1476.930000
14      13132    28.058325   36.263175   589.290336
15      30954    28.058325   36.263175   589.290336
16      45532     0.000000    0.000000    89.940000
17     180038    30.000000   16.720000   374.070000
18      14869     2.000000   13.240000   112.500000
19     261721   146.000000   49.940000   772.770000
20      50889    28.058325   36.263175   589.290336
21    7322564  2818.000000   38.500000  2097.710000
22      26436     9.000000   58.030000   644.750000
23      12183     1.000000    8.070000   145.200000
24      16023    10.000000   55.520000   560.710000
25      24692     9.000000   29.180000   204.230000
26      13842     2.000000   13.380000   347.970000
27      88693    42.000000   45.100000   894.510000
28      11235    20.000000  145.720000  1143.900000
29      28259    24.000000   86.130000   724.950000
...       ...          ...         ...          ...
2185    48949    33.000000   60.080000  1691.210000
2186    23252     4.000000   14.990000   741.910000
2187    15066     3.000000   19.130000   216.850000
2188    13198     1.000000    7.370000    73.730000
2189    16829     1.000000    5.070000   324.660000
2190    15372     1.000000    6.280000    43.980000
2191    13333     4.000000   29.140000   254.930000
2192    37825     7.000000   17.720000   255.740000
2193    29885     7.000000   18.830000   492.400000
2194    37520     3.000000    7.140000   228.530000
2195    20319     3.000000   13.000000   485.180000
2196    77759    56.000000   69.620000  1246.890000
2197    14904     2.000000    9.800000   205.840000
2198    12208     1.000000    8.080000   234.340000
2199    25430     4.000000   14.980000    86.120000
2200    92703     9.000000   10.010000   640.620000
2201    24544    15.000000   59.710000   409.980000
2202    14203     4.000000   24.370000   255.860000
2203    27331     8.000000   27.530000  1996.150000
2204    23875     6.000000   21.950000   288.980000
2205    14804     6.000000   32.870000   372.560000
2206    21732     6.000000   26.900000   228.660000
2207    54021     5.000000    9.460000   285.730000
2208    13131     1.000000    7.810000    46.850000
2209    10567     0.000000    0.000000   132.870000
2210    56216    30.000000   49.460000   545.750000
2211    12251     4.000000   33.090000   124.100000
2212    32824     5.000000   13.610000   353.830000
2213    13547     2.000000   15.710000   691.170000
2214    28898    19.000000   62.800000   918.890000

[2215 rows x 4 columns]

In [42]:
#menyimpan file data tanpa missing value
from pandas import DataFrame
datacrimetmv = pd.DataFrame(datacrime1,columns=['respon','predik1','predik2','predik3'])
datacrimetmv.to_excel ("datacrime_tanpa_mv.xlsx")

In [43]:
#mengatasi outlier
datacrime2=datacrime1
from scipy import stats
z = np.abs(stats.zscore(datacrime2._get_numeric_data()))
print(z)
datacrime2 = datacrime2[(z < 3).all(axis=1)]
print(datacrime.shape)
datacrime2

[[0.20109091 0.2791634  1.11292231 0.94027795]
 [0.14662164 0.26921401 0.98248917 0.79186275]
 [0.11621212 0.21946702 0.60346581 0.63574724]
 ...
 [0.09920116 0.22941642 0.69522936 0.40381204]
 [0.1934311  0.25926461 0.63078005 0.17472257]
 [0.11839226 0.09012487 0.81441914 0.56526001]]
(2215, 4)


respon     predik1     predik2      predik3
0      11980    0.000000    0.000000    41.020000
1      23123    1.000000    4.250000   127.560000
2      29344    6.000000   16.600000   218.590000
3      16656   10.000000   57.860000   306.640000
4      11245   28.058325   36.263175   589.290336
5     140494   77.000000   50.980000   442.950000
6      28700    4.000000   13.530000   226.630000
7      59459   34.000000   55.790000   439.730000
8      74111   35.000000   43.870000   115.310000
9     103590  141.000000  130.690000  1544.240000
10     31601   29.000000   90.250000   722.020000
12     40641   36.000000   78.530000   798.390000
13     57140   59.000000  100.510000  1476.930000
14     13132   28.058325   36.263175   589.290336
15     30954   28.058325   36.263175   589.290336
16     45532    0.000000    0.000000    89.940000
17    180038   30.000000   16.720000   374.070000
18     14869    2.000000   13.240000   112.500000
19    261721  146.000000   49.940000   772.770000
20     50889   28.058325   36.263175   589.290336
22     26436    9.000000   58.030000   644.750000
23     12183    1.000000    8.070000   145.200000
24     16023   10.000000   55.520000   560.710000
25     24692    9.000000   29.180000   204.230000
26     13842    2.000000   13.380000   347.970000
27     88693   42.000000   45.100000   894.510000
29     28259   24.000000   86.130000   724.950000
30     11162    2.000000   17.400000  1487.340000
31    122899    7.000000    4.580000   689.420000
32     20714    3.000000   14.980000    49.930000
...      ...         ...         ...          ...
2185   48949   33.000000   60.080000  1691.210000
2186   23252    4.000000   14.990000   741.910000
2187   15066    3.000000   19.130000   216.850000
2188   13198    1.000000    7.370000    73.730000
2189   16829    1.000000    5.070000   324.660000
2190   15372    1.000000    6.280000    43.980000
2191   13333    4.000000   29.140000   254.930000
2192   37825    7.000000   17.720000   255.740000
2193   29885    7.000000   18.830000   492.400000
2194   37520    3.000000    7.140000   228.530000
2195   20319    3.000000   13.000000   485.180000
2196   77759   56.000000   69.620000  1246.890000
2197   14904    2.000000    9.800000   205.840000
2198   12208    1.000000    8.080000   234.340000
2199   25430    4.000000   14.980000    86.120000
2200   92703    9.000000   10.010000   640.620000
2201   24544   15.000000   59.710000   409.980000
2202   14203    4.000000   24.370000   255.860000
2203   27331    8.000000   27.530000  1996.150000
2204   23875    6.000000   21.950000   288.980000
2205   14804    6.000000   32.870000   372.560000
2206   21732    6.000000   26.900000   228.660000
2207   54021    5.000000    9.460000   285.730000
2208   13131    1.000000    7.810000    46.850000
2209   10567    0.000000    0.000000   132.870000
2210   56216   30.000000   49.460000   545.750000
2211   12251    4.000000   33.090000   124.100000
2212   32824    5.000000   13.610000   353.830000
2213   13547    2.000000   15.710000   691.170000
2214   28898   19.000000   62.800000   918.890000

[2116 rows x 4 columns]

In [44]:
#menyimpan file data tanpa missing value dan outlier
from pandas import DataFrame
datacrimenoout = pd.DataFrame(datacrime2,columns=['respon','predik1','predik2','predik3'])
datacrimenoout.to_excel ("datacrime_tanpa_outlier.xlsx")

In [45]:
#normalisasi data yang belum diatasi outliernya
from sklearn.preprocessing import normalize
datacrime3=normalize(datacrime1,norm='l2') #default norm L2, other are L1 and max
datacrime3=pd.DataFrame(datacrime3)
datacrime3

0         1         2         3
0     0.999994  0.000000  0.000000  0.003424
1     0.999985  0.000043  0.000184  0.005517
2     0.999972  0.000204  0.000566  0.007449
3     0.999824  0.000600  0.003473  0.018407
4     0.998621  0.002492  0.003220  0.052332
5     0.999995  0.000548  0.000363  0.003153
6     0.999969  0.000139  0.000471  0.007896
7     0.999972  0.000572  0.000938  0.007395
8     0.999999  0.000472  0.000592  0.001556
9     0.999887  0.001361  0.001261  0.014906
10    0.999735  0.000917  0.002855  0.022842
11    0.994673  0.000830  0.003073  0.103032
12    0.999805  0.000886  0.001932  0.019641
13    0.999664  0.001032  0.001758  0.025839
14    0.998989  0.002134  0.002759  0.044829
15    0.999818  0.000906  0.001171  0.019034
16    0.999998  0.000000  0.000000  0.001975
17    0.999998  0.000167  0.000093  0.002078
18    0.999971  0.000135  0.000890  0.007566
19    0.999995  0.000558  0.000191  0.002953
20    0.999933  0.000551  0.000713  0.011579
21    1.000000  0.000385  0.000005  0.000286
22    0.999700  0.000340  0.002194  0.024382
23    0.999929  0.000082  0.000662  0.011917
24    0.999382  0.000624  0.003463  0.034972
25    0.999965  0.000364  0.001182  0.008271
26    0.999684  0.000144  0.000966  0.025131
27    0.999949  0.000474  0.000508  0.010085
28    0.994772  0.001771  0.012902  0.101283
29    0.999666  0.000849  0.003047  0.025645
...        ...       ...       ...       ...
2185  0.999403  0.000674  0.001227  0.034530
2186  0.999491  0.000172  0.000644  0.031891
2187  0.999896  0.000199  0.001270  0.014392
2188  0.999984  0.000076  0.000558  0.005586
2189  0.999814  0.000059  0.000301  0.019288
2190  0.999996  0.000065  0.000409  0.002861
2191  0.999815  0.000300  0.002185  0.019117
2192  0.999977  0.000185  0.000468  0.006761
2193  0.999864  0.000234  0.000630  0.016474
2194  0.999981  0.000080  0.000190  0.006091
2195  0.999715  0.000148  0.000640  0.023871
2196  0.999871  0.000720  0.000895  0.016033
2197  0.999904  0.000134  0.000657  0.013810
2198  0.999816  0.000082  0.000662  0.019192
2199  0.999994  0.000157  0.000589  0.003387
2200  0.999976  0.000097  0.000108  0.006910
2201  0.999857  0.000611  0.002432  0.016701
2202  0.999836  0.000282  0.001716  0.018012
2203  0.997343  0.000292  0.001005  0.072842
2204  0.999926  0.000251  0.000919  0.012103
2205  0.999681  0.000405  0.002220  0.025158
2206  0.999944  0.000276  0.001238  0.010521
2207  0.999986  0.000093  0.000175  0.005289
2208  0.999993  0.000076  0.000595  0.003568
2209  0.999921  0.000000  0.000000  0.012573
2210  0.999952  0.000534  0.000880  0.009708
2211  0.999945  0.000326  0.002701  0.010129
2212  0.999942  0.000152  0.000415  0.010779
2213  0.998700  0.000147  0.001158  0.050954
2214  0.999492  0.000657  0.002172  0.031782

[2215 rows x 4 columns]

In [46]:
#transformasi datacrime3 menggunakan metode 3sigmoidal
datacrime3trans=(1-2.718281828**(datacrime3))/(1+2.718281828**(datacrime3))
datacrime3trans

0         1         2         3
0    -0.462115  0.000000  0.000000 -0.001712
1    -0.462111 -0.000022 -0.000092 -0.002758
2    -0.462106 -0.000102 -0.000283 -0.003724
3    -0.462048 -0.000300 -0.001737 -0.009203
4    -0.461575 -0.001246 -0.001610 -0.026160
5    -0.462115 -0.000274 -0.000181 -0.001576
6    -0.462105 -0.000070 -0.000236 -0.003948
7    -0.462106 -0.000286 -0.000469 -0.003698
8    -0.462117 -0.000236 -0.000296 -0.000778
9    -0.462073 -0.000680 -0.000631 -0.007453
10   -0.462013 -0.000459 -0.001428 -0.011420
11   -0.460020 -0.000415 -0.001537 -0.051470
12   -0.462040 -0.000443 -0.000966 -0.009820
13   -0.461985 -0.000516 -0.000879 -0.012919
14   -0.461719 -0.001067 -0.001379 -0.022411
15   -0.462045 -0.000453 -0.000586 -0.009517
16   -0.462116  0.000000  0.000000 -0.000988
17   -0.462116 -0.000083 -0.000046 -0.001039
18   -0.462106 -0.000067 -0.000445 -0.003783
19   -0.462115 -0.000279 -0.000095 -0.001476
20   -0.462091 -0.000276 -0.000356 -0.005790
21   -0.462117 -0.000192 -0.000003 -0.000143
22   -0.461999 -0.000170 -0.001097 -0.012190
23   -0.462089 -0.000041 -0.000331 -0.005959
24   -0.461874 -0.000312 -0.001731 -0.017484
25   -0.462103 -0.000182 -0.000591 -0.004135
26   -0.461993 -0.000072 -0.000483 -0.012565
27   -0.462097 -0.000237 -0.000254 -0.005042
28   -0.460059 -0.000885 -0.006451 -0.050599
29   -0.461986 -0.000425 -0.001523 -0.012822
...        ...       ...       ...       ...
2185 -0.461882 -0.000337 -0.000613 -0.017263
2186 -0.461917 -0.000086 -0.000322 -0.015944
2187 -0.462076 -0.000100 -0.000635 -0.007196
2188 -0.462111 -0.000038 -0.000279 -0.002793
2189 -0.462044 -0.000030 -0.000151 -0.009644
2190 -0.462116 -0.000033 -0.000204 -0.001431
2191 -0.462044 -0.000150 -0.001093 -0.009558
2192 -0.462108 -0.000093 -0.000234 -0.003380
2193 -0.462064 -0.000117 -0.000315 -0.008237
2194 -0.462110 -0.000040 -0.000095 -0.003045
2195 -0.462005 -0.000074 -0.000320 -0.011935
2196 -0.462066 -0.000360 -0.000448 -0.008016
2197 -0.462080 -0.000067 -0.000329 -0.006905
2198 -0.462045 -0.000041 -0.000331 -0.009596
2199 -0.462115 -0.000079 -0.000295 -0.001693
2200 -0.462108 -0.000049 -0.000054 -0.003455
2201 -0.462061 -0.000306 -0.001216 -0.008351
2202 -0.462053 -0.000141 -0.000858 -0.009006
2203 -0.461072 -0.000146 -0.000502 -0.036405
2204 -0.462088 -0.000126 -0.000460 -0.006051
2205 -0.461992 -0.000203 -0.001110 -0.012578
2206 -0.462095 -0.000138 -0.000619 -0.005261
2207 -0.462112 -0.000046 -0.000088 -0.002645
2208 -0.462115 -0.000038 -0.000297 -0.001784
2209 -0.462086  0.000000  0.000000 -0.006286
2210 -0.462098 -0.000267 -0.000440 -0.004854
2211 -0.462096 -0.000163 -0.001350 -0.005065
2212 -0.462094 -0.000076 -0.000207 -0.005389
2213 -0.461606 -0.000074 -0.000579 -0.025471
2214 -0.461917 -0.000329 -0.001086 -0.015889

[2215 rows x 4 columns]

In [50]:
#menyimpan file data transformasi with outlier
from pandas import DataFrame
datacrimenormout = pd.DataFrame(datacrime3trans)
datacrimenormout.to_excel ("datacrime_trans_outlier.xlsx")
datacrimenormout

0         1         2         3
0    -0.462115  0.000000  0.000000 -0.001712
1    -0.462111 -0.000022 -0.000092 -0.002758
2    -0.462106 -0.000102 -0.000283 -0.003724
3    -0.462048 -0.000300 -0.001737 -0.009203
4    -0.461575 -0.001246 -0.001610 -0.026160
5    -0.462115 -0.000274 -0.000181 -0.001576
6    -0.462105 -0.000070 -0.000236 -0.003948
7    -0.462106 -0.000286 -0.000469 -0.003698
8    -0.462117 -0.000236 -0.000296 -0.000778
9    -0.462073 -0.000680 -0.000631 -0.007453
10   -0.462013 -0.000459 -0.001428 -0.011420
11   -0.460020 -0.000415 -0.001537 -0.051470
12   -0.462040 -0.000443 -0.000966 -0.009820
13   -0.461985 -0.000516 -0.000879 -0.012919
14   -0.461719 -0.001067 -0.001379 -0.022411
15   -0.462045 -0.000453 -0.000586 -0.009517
16   -0.462116  0.000000  0.000000 -0.000988
17   -0.462116 -0.000083 -0.000046 -0.001039
18   -0.462106 -0.000067 -0.000445 -0.003783
19   -0.462115 -0.000279 -0.000095 -0.001476
20   -0.462091 -0.000276 -0.000356 -0.005790
21   -0.462117 -0.000192 -0.000003 -0.000143
22   -0.461999 -0.000170 -0.001097 -0.012190
23   -0.462089 -0.000041 -0.000331 -0.005959
24   -0.461874 -0.000312 -0.001731 -0.017484
25   -0.462103 -0.000182 -0.000591 -0.004135
26   -0.461993 -0.000072 -0.000483 -0.012565
27   -0.462097 -0.000237 -0.000254 -0.005042
28   -0.460059 -0.000885 -0.006451 -0.050599
29   -0.461986 -0.000425 -0.001523 -0.012822
...        ...       ...       ...       ...
2185 -0.461882 -0.000337 -0.000613 -0.017263
2186 -0.461917 -0.000086 -0.000322 -0.015944
2187 -0.462076 -0.000100 -0.000635 -0.007196
2188 -0.462111 -0.000038 -0.000279 -0.002793
2189 -0.462044 -0.000030 -0.000151 -0.009644
2190 -0.462116 -0.000033 -0.000204 -0.001431
2191 -0.462044 -0.000150 -0.001093 -0.009558
2192 -0.462108 -0.000093 -0.000234 -0.003380
2193 -0.462064 -0.000117 -0.000315 -0.008237
2194 -0.462110 -0.000040 -0.000095 -0.003045
2195 -0.462005 -0.000074 -0.000320 -0.011935
2196 -0.462066 -0.000360 -0.000448 -0.008016
2197 -0.462080 -0.000067 -0.000329 -0.006905
2198 -0.462045 -0.000041 -0.000331 -0.009596
2199 -0.462115 -0.000079 -0.000295 -0.001693
2200 -0.462108 -0.000049 -0.000054 -0.003455
2201 -0.462061 -0.000306 -0.001216 -0.008351
2202 -0.462053 -0.000141 -0.000858 -0.009006
2203 -0.461072 -0.000146 -0.000502 -0.036405
2204 -0.462088 -0.000126 -0.000460 -0.006051
2205 -0.461992 -0.000203 -0.001110 -0.012578
2206 -0.462095 -0.000138 -0.000619 -0.005261
2207 -0.462112 -0.000046 -0.000088 -0.002645
2208 -0.462115 -0.000038 -0.000297 -0.001784
2209 -0.462086  0.000000  0.000000 -0.006286
2210 -0.462098 -0.000267 -0.000440 -0.004854
2211 -0.462096 -0.000163 -0.001350 -0.005065
2212 -0.462094 -0.000076 -0.000207 -0.005389
2213 -0.461606 -0.000074 -0.000579 -0.025471
2214 -0.461917 -0.000329 -0.001086 -0.015889

[2215 rows x 4 columns]

In [51]:
#normalisasi data yang sudah diatasi outliernya
from sklearn.preprocessing import normalize
datacrime4=normalize(datacrime2,norm='l2') #default norm L2, other are L1 and max
datacrime4=pd.DataFrame(datacrime4)
datacrime4

0         1         2         3
0     0.999994  0.000000  0.000000  0.003424
1     0.999985  0.000043  0.000184  0.005517
2     0.999972  0.000204  0.000566  0.007449
3     0.999824  0.000600  0.003473  0.018407
4     0.998621  0.002492  0.003220  0.052332
5     0.999995  0.000548  0.000363  0.003153
6     0.999969  0.000139  0.000471  0.007896
7     0.999972  0.000572  0.000938  0.007395
8     0.999999  0.000472  0.000592  0.001556
9     0.999887  0.001361  0.001261  0.014906
10    0.999735  0.000917  0.002855  0.022842
11    0.999805  0.000886  0.001932  0.019641
12    0.999664  0.001032  0.001758  0.025839
13    0.998989  0.002134  0.002759  0.044829
14    0.999818  0.000906  0.001171  0.019034
15    0.999998  0.000000  0.000000  0.001975
16    0.999998  0.000167  0.000093  0.002078
17    0.999971  0.000135  0.000890  0.007566
18    0.999995  0.000558  0.000191  0.002953
19    0.999933  0.000551  0.000713  0.011579
20    0.999700  0.000340  0.002194  0.024382
21    0.999929  0.000082  0.000662  0.011917
22    0.999382  0.000624  0.003463  0.034972
23    0.999965  0.000364  0.001182  0.008271
24    0.999684  0.000144  0.000966  0.025131
25    0.999949  0.000474  0.000508  0.010085
26    0.999666  0.000849  0.003047  0.025645
27    0.991237  0.000178  0.001545  0.132083
28    0.999984  0.000057  0.000037  0.005610
29    0.999997  0.000145  0.000723  0.002410
...        ...       ...       ...       ...
2086  0.999403  0.000674  0.001227  0.034530
2087  0.999491  0.000172  0.000644  0.031891
2088  0.999896  0.000199  0.001270  0.014392
2089  0.999984  0.000076  0.000558  0.005586
2090  0.999814  0.000059  0.000301  0.019288
2091  0.999996  0.000065  0.000409  0.002861
2092  0.999815  0.000300  0.002185  0.019117
2093  0.999977  0.000185  0.000468  0.006761
2094  0.999864  0.000234  0.000630  0.016474
2095  0.999981  0.000080  0.000190  0.006091
2096  0.999715  0.000148  0.000640  0.023871
2097  0.999871  0.000720  0.000895  0.016033
2098  0.999904  0.000134  0.000657  0.013810
2099  0.999816  0.000082  0.000662  0.019192
2100  0.999994  0.000157  0.000589  0.003387
2101  0.999976  0.000097  0.000108  0.006910
2102  0.999857  0.000611  0.002432  0.016701
2103  0.999836  0.000282  0.001716  0.018012
2104  0.997343  0.000292  0.001005  0.072842
2105  0.999926  0.000251  0.000919  0.012103
2106  0.999681  0.000405  0.002220  0.025158
2107  0.999944  0.000276  0.001238  0.010521
2108  0.999986  0.000093  0.000175  0.005289
2109  0.999993  0.000076  0.000595  0.003568
2110  0.999921  0.000000  0.000000  0.012573
2111  0.999952  0.000534  0.000880  0.009708
2112  0.999945  0.000326  0.002701  0.010129
2113  0.999942  0.000152  0.000415  0.010779
2114  0.998700  0.000147  0.001158  0.050954
2115  0.999492  0.000657  0.002172  0.031782

[2116 rows x 4 columns]

In [52]:
#transformasi datacrime4 menggunakan metode 3sigmoidal
datacrime4trans=(1-2.718281828**(datacrime4))/(1+2.718281828**(datacrime4))
datacrime4trans

0         1         2         3
0    -0.462115  0.000000  0.000000 -0.001712
1    -0.462111 -0.000022 -0.000092 -0.002758
2    -0.462106 -0.000102 -0.000283 -0.003724
3    -0.462048 -0.000300 -0.001737 -0.009203
4    -0.461575 -0.001246 -0.001610 -0.026160
5    -0.462115 -0.000274 -0.000181 -0.001576
6    -0.462105 -0.000070 -0.000236 -0.003948
7    -0.462106 -0.000286 -0.000469 -0.003698
8    -0.462117 -0.000236 -0.000296 -0.000778
9    -0.462073 -0.000680 -0.000631 -0.007453
10   -0.462013 -0.000459 -0.001428 -0.011420
11   -0.462040 -0.000443 -0.000966 -0.009820
12   -0.461985 -0.000516 -0.000879 -0.012919
13   -0.461719 -0.001067 -0.001379 -0.022411
14   -0.462045 -0.000453 -0.000586 -0.009517
15   -0.462116  0.000000  0.000000 -0.000988
16   -0.462116 -0.000083 -0.000046 -0.001039
17   -0.462106 -0.000067 -0.000445 -0.003783
18   -0.462115 -0.000279 -0.000095 -0.001476
19   -0.462091 -0.000276 -0.000356 -0.005790
20   -0.461999 -0.000170 -0.001097 -0.012190
21   -0.462089 -0.000041 -0.000331 -0.005959
22   -0.461874 -0.000312 -0.001731 -0.017484
23   -0.462103 -0.000182 -0.000591 -0.004135
24   -0.461993 -0.000072 -0.000483 -0.012565
25   -0.462097 -0.000237 -0.000254 -0.005042
26   -0.461986 -0.000425 -0.001523 -0.012822
27   -0.458665 -0.000089 -0.000773 -0.065946
28   -0.462111 -0.000028 -0.000019 -0.002805
29   -0.462116 -0.000072 -0.000362 -0.001205
...        ...       ...       ...       ...
2086 -0.461882 -0.000337 -0.000613 -0.017263
2087 -0.461917 -0.000086 -0.000322 -0.015944
2088 -0.462076 -0.000100 -0.000635 -0.007196
2089 -0.462111 -0.000038 -0.000279 -0.002793
2090 -0.462044 -0.000030 -0.000151 -0.009644
2091 -0.462116 -0.000033 -0.000204 -0.001431
2092 -0.462044 -0.000150 -0.001093 -0.009558
2093 -0.462108 -0.000093 -0.000234 -0.003380
2094 -0.462064 -0.000117 -0.000315 -0.008237
2095 -0.462110 -0.000040 -0.000095 -0.003045
2096 -0.462005 -0.000074 -0.000320 -0.011935
2097 -0.462066 -0.000360 -0.000448 -0.008016
2098 -0.462080 -0.000067 -0.000329 -0.006905
2099 -0.462045 -0.000041 -0.000331 -0.009596
2100 -0.462115 -0.000079 -0.000295 -0.001693
2101 -0.462108 -0.000049 -0.000054 -0.003455
2102 -0.462061 -0.000306 -0.001216 -0.008351
2103 -0.462053 -0.000141 -0.000858 -0.009006
2104 -0.461072 -0.000146 -0.000502 -0.036405
2105 -0.462088 -0.000126 -0.000460 -0.006051
2106 -0.461992 -0.000203 -0.001110 -0.012578
2107 -0.462095 -0.000138 -0.000619 -0.005261
2108 -0.462112 -0.000046 -0.000088 -0.002645
2109 -0.462115 -0.000038 -0.000297 -0.001784
2110 -0.462086  0.000000  0.000000 -0.006286
2111 -0.462098 -0.000267 -0.000440 -0.004854
2112 -0.462096 -0.000163 -0.001350 -0.005065
2113 -0.462094 -0.000076 -0.000207 -0.005389
2114 -0.461606 -0.000074 -0.000579 -0.025471
2115 -0.461917 -0.000329 -0.001086 -0.015889

[2116 rows x 4 columns]

In [53]:
#menyimpan file data normalisasi no outlier
from pandas import DataFrame
datacrimenorm = pd.DataFrame(datacrime4trans)
datacrimenorm.to_excel ("datacrime_transformasi.xlsx")

#source https://archive.ics.uci.edu/ml/datasets.html